
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

package calculadorahoc3;

/** CUP generated class containing symbol constants. */
public class AnalizadorSintacticoSym {
  /* terminals */
  public static final int NUM = 11;
  public static final int POW = 15;
  public static final int ParDer = 8;
  public static final int UMINUS = 14;
  public static final int ENTER = 9;
  public static final int CONSTS = 12;
  public static final int EOF = 0;
  public static final int opRESTA = 3;
  public static final int VAR = 13;
  public static final int opSUMA = 2;
  public static final int ASIG = 6;
  public static final int opMULT = 4;
  public static final int error = 1;
  public static final int SEMICOLON = 10;
  public static final int opDIV = 5;
  public static final int ParIzq = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "opSUMA",
  "opRESTA",
  "opMULT",
  "opDIV",
  "ASIG",
  "ParIzq",
  "ParDer",
  "ENTER",
  "SEMICOLON",
  "NUM",
  "CONSTS",
  "VAR",
  "UMINUS",
  "POW"
  };
}

