package calculadorahoc3;

import java_cup.runtime.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.io.BufferedReader;
import java.util.logging.Level;
import java.util.logging.Logger;

public class HOC3JFrame extends javax.swing.JFrame {

    /**
     * Creates new form HOC3JFrame
     */
    public HOC3JFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLexico = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSintactico = new javax.swing.JTextArea();
        BotonLimpiar = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        BotonLexic = new javax.swing.JButton();
        BotonSintac = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        txtLexico.setColumns(20);
        txtLexico.setRows(5);
        jScrollPane2.setViewportView(txtLexico);

        txtSintactico.setColumns(20);
        txtSintactico.setRows(5);
        jScrollPane3.setViewportView(txtSintactico);

        BotonLimpiar.setText("Limpiar");
        BotonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLimpiarActionPerformed(evt);
            }
        });

        BotonSalir.setText("Salir");
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        BotonLexic.setText("Analizar Lexicamente");
        BotonLexic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLexicActionPerformed(evt);
            }
        });

        BotonSintac.setText("Analizar Sintacticamente");
        BotonSintac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSintacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(BotonLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonSalir)
                        .addGap(37, 37, 37))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(BotonLexic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotonSintac)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BotonLimpiar)
                            .addComponent(BotonSalir))))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonLexic)
                    .addComponent(BotonSintac))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLimpiarActionPerformed
        txtArea.setText("");
        txtLexico.setText("");
        txtSintactico.setText("");
    }//GEN-LAST:event_BotonLimpiarActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void BotonLexicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLexicActionPerformed
        Symbol simb;
        String Lexema = new String();
        String CadAux = new String();
        File ArchEntrada = new File("./ArchEntrada.txt");
        PrintWriter escribir;
        txtLexico.setText("");
        txtSintactico.setText("");
        try{
            escribir = new PrintWriter(ArchEntrada);
            escribir.print(txtArea.getText());
            escribir.close();
        }catch(FileNotFoundException ex){
            Logger.getLogger(HOC3JFrame.class.getName()).log(Level.SEVERE,null,ex);
        }
        
        try{
            Reader lector;
            lector = new BufferedReader(new FileReader("./ArchEntrada.txt"));
            
            AnalizadorLexico AnalysLex = new AnalizadorLexico(lector);
            
            do{
                simb = AnalysLex.next_token();
                CadAux = Integer.toString(simb.sym);
                Lexema = AnalysLex.yytext();
                if(simb.sym == AnalizadorSintacticoSym.EOF)
                    CadAux = "Token: "+CadAux+"\tIdentToken: FIN\n";
                else{
                    switch(simb.sym){
                        case AnalizadorSintacticoSym.SEMICOLON:
                            CadAux = "Token: "+CadAux+"\tIdentToken: SEMICOLON\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.ENTER:
                            CadAux = "Token: "+CadAux+"\tIdentToken: Enter\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.NUM:
                            CadAux = "Token: "+CadAux+"\tIdentToken: NUM\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.opSUMA:
                            CadAux = "Token: "+CadAux+"\tIdentToken: SUMA\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.opRESTA:
                            CadAux = "Token: "+CadAux+"\tIdentToken: RESTA\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.opMULT:
                            CadAux = "Token: "+CadAux+"\tIdentToken: MULT\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.opDIV:
                            CadAux = "Token: "+CadAux+"\tIdentToken: DIV\t\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.ASIG:
                            CadAux = "Token: "+CadAux+"\tIdentToken: ASIG\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.ParIzq:
                            CadAux = "Token: "+CadAux+"\tIdentToken: ParIzq\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.ParDer:
                            CadAux = "Token: "+CadAux+"\tIdentToken: ParDer\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.error:
                            CadAux = "Token: "+CadAux+"\tIdentToken: error\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.POW:
                            CadAux = "Token: "+CadAux+"\tIdentToken: POW\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.BLTIN:
                            CadAux = "Token: "+CadAux+"\tIdentToken: BLTIN\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.CONSTS:
                            CadAux = "Token: "+CadAux+"\tIdentToken: CONSTS\t Lexema: "+Lexema+"\n";
                        break;
                        case AnalizadorSintacticoSym.VAR:
                            CadAux = "Token: "+CadAux+"\tIdentToken: VAR\t Lexema: "+Lexema+" indice="+Integer.toString((Integer) simb.value)+"\n";
                        break;
                        default:
                            CadAux = "Token: "+CadAux+"\tIdentToken: OTRO\t Lexema: "+AnalysLex.yytext()+"\n";
                        break;
                    }
                }
                txtLexico.append(CadAux);
            }while(simb.sym != AnalizadorSintacticoSym.EOF);
        }catch(IOException ex){
            txtLexico.append("Entro\' al catch");
            Logger.getLogger(HOC3JFrame.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_BotonLexicActionPerformed

    private void BotonSintacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSintacActionPerformed
        try{
            AnalizadorSintactico AnalySintac = new AnalizadorSintactico(
                        new AnalizadorLexico(new FileReader("./ArchEntrada.txt")));
            AnalySintac.frmInterfaz = this;
            Object result = AnalySintac.parse().value;
            txtSintactico.append("\nFin del analisis");
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_BotonSintacActionPerformed

    public void PonerTextSintac(String ss){
        txtSintactico.append(ss);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLexic;
    private javax.swing.JButton BotonLimpiar;
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonSintac;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextArea txtLexico;
    private javax.swing.JTextArea txtSintactico;
    // End of variables declaration//GEN-END:variables
}
